package com.bootcamp.entity.email;
public enum EmailType {
    ACCOUNT_LOCKED,
    SELLER_REGISTERED,
    CUSTOMER_ACTIVATE_ACCOUNT,
    USER_ACCOUNT_ACTIVATED,
    ACTIVATE_PRODUCT,
    USER_ACCOUNT_DEACTIVATED,
    FORGOT_PASSWORD_GENERATE,
    PASSWORD_UPDATED,
    PRODUCT_ACTIVATED,
    PRODUCT_DEACTIVATED,

}
