spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=19082003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
logging.level.com.bootcamp=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aryan.kohli@tothenew.com
spring.mail.password=vohp vmja iubq wpfi  
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.token.secret=5367566859703373367639792F423F452848284D6251655468576D5A71347437
jwt.access.token.secret=DN38HEJ8BEHJAT3HG92GUOHUI6F98Y4H7CGYGD37GFD3YHY3G7H

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

image.base-path=/home/aryan/aryan_bootcamp_project/Bootcamp/src/main/resources/images
image.user.profile-pic=/users/profile-pic
image.user.product=/product
server.address = 0.0.0.0
server.port=8080
#server.tomcat.relaxed-query-chars=^
management.endpoints.web.exposure.include=*
